# Generated by Django 5.1.6 on 2025-02-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('Ремонт', 'Ремонт'), ('Покупки', 'Покупки'), ('Уборка', 'Уборка'), ('Слушатель', 'Слушатель'), ('Другое', 'Другое')], max_length=50, verbose_name='Тип задания')),
                ('preferred_gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Не важно', 'Не важно')], max_length=20, verbose_name='Предпочитаемый пол')),
                ('urgency', models.CharField(choices=[('Срочно', 'Срочно'), ('Не особо срочно', 'Не особо срочно'), ('Выбор времени', 'Выбор времени')], max_length=50, verbose_name='Срочность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
