# Generated by Django 5.0.4 on 2025-02-19 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
        ('authentication', '0003_remove_user_can_help_remove_user_need_help_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='announcement.announcement')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_responses', to='authentication.user')),
            ],
        ),
    ]
