# Generated by Django 5.0.4 on 2025-02-19 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_help',
        ),
        migrations.RemoveField(
            model_name='user',
            name='need_help',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pensioner',
            field=models.BooleanField(default=False, verbose_name='Пенсионер'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, verbose_name='Волонтёр'),
        ),
        migrations.CreateModel(
            name='PensionerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pensioner_profile', to='authentication.user')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='Опыт')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to='authentication.user')),
            ],
        ),
    ]
