# Generated by Django 5.2 on 2025-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_can_help_remove_user_need_help_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_volunteer',
        ),
        migrations.AddField(
            model_name='pensionerprofile',
            name='actual_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фактический адрес проживания'),
        ),
        migrations.AddField(
            model_name='pensionerprofile',
            name='is_same_address',
            field=models.BooleanField(default=False, verbose_name='Адреса совпадают'),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issue_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_issued_by',
            field=models.CharField(max_length=255, null=True, verbose_name='Кем выдан паспорт'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=models.CharField(max_length=6, null=True, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=models.CharField(max_length=4, null=True, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='company_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Компания/Организация'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Фото профиля'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='work_zone',
            field=models.CharField(max_length=255, null=True, verbose_name='Зона работы'),
        ),
        migrations.AlterField(
            model_name='pensionerprofile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес регистрации'),
        ),
    ]
