# Generated by Django 5.2 on 2025-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_date_user_date_of_birth_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False, verbose_name='Волонтёр'),
        ),
    ]
